name: examen-workflow

on: 
  push:
    branches:
      - nueva-característica

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar Código
        uses: actions/checkout@v2

      - name: Configurar entorno python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar pytest
        run: pip install pytest

      - name: ejecutar codigo
        run: pytest test.py

      - name: Construir imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          
