name: prueba

on: push

jobs:
  tareas: 
    runs-on: ubuntu-latest

    steps:
      - name: descargar code
        uses: actions/checkout@v4

      - name: instalar dependencias
        run: pip install pytest

      - name: probar code
        run: pytest test.py
        
